-- Create Database
CREATE DATABASE IF NOT EXISTS FilmLane;
USE FilmLane;

-- Users Table
CREATE TABLE User (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) UNIQUE NOT NULL,
  passwordHash VARCHAR(255) NOT NULL,
  username VARCHAR(50),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Password Reset Tokens
CREATE TABLE PasswordResetToken (
  id INT PRIMARY KEY AUTO_INCREMENT,
  token VARCHAR(255) UNIQUE NOT NULL,
  expiresAt DATETIME NOT NULL,
  userId INT NOT NULL,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Watchlist
CREATE TABLE WatchlistItem (
  id INT PRIMARY KEY AUTO_INCREMENT,
  userId INT NOT NULL,
  tmdbId INT NOT NULL,
  addedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  UNIQUE KEY unique_watchlist (userId, tmdbId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Watch History
CREATE TABLE WatchHistory (
  id INT PRIMARY KEY AUTO_INCREMENT,
  userId INT NOT NULL,
  tmdbId INT NOT NULL,
  watchedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  progress FLOAT CHECK (progress BETWEEN 0 AND 100),
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  INDEX idx_user (userId),
  INDEX idx_tmdb (tmdbId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;